//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.269.
// 
#pragma warning disable 1591

namespace API_Example.DataService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Data ServiceSoap", Namespace="http://clients.mindbodyonline.com/api/0_5")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MBResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MBRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Row[]))]
    public partial class DataService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SelectDataXmlOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelectDataCSVOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelectAggregateDataXmlOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelectAggregateDataCSVOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DataService() {
            this.Url = global::API_Example.Properties.Settings.Default.API_Example_mindbodyonline_api_dataservice_Data_x0020_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SelectDataXmlCompletedEventHandler SelectDataXmlCompleted;
        
        /// <remarks/>
        public event SelectDataCSVCompletedEventHandler SelectDataCSVCompleted;
        
        /// <remarks/>
        public event SelectAggregateDataXmlCompletedEventHandler SelectAggregateDataXmlCompleted;
        
        /// <remarks/>
        public event SelectAggregateDataCSVCompletedEventHandler SelectAggregateDataCSVCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://clients.mindbodyonline.com/api/0_5/SelectDataXml", RequestNamespace="http://clients.mindbodyonline.com/api/0_5", ResponseNamespace="http://clients.mindbodyonline.com/api/0_5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SelectDataXmlResult SelectDataXml(SelectDataXmlRequest Request) {
            object[] results = this.Invoke("SelectDataXml", new object[] {
                        Request});
            return ((SelectDataXmlResult)(results[0]));
        }
        
        /// <remarks/>
        public void SelectDataXmlAsync(SelectDataXmlRequest Request) {
            this.SelectDataXmlAsync(Request, null);
        }
        
        /// <remarks/>
        public void SelectDataXmlAsync(SelectDataXmlRequest Request, object userState) {
            if ((this.SelectDataXmlOperationCompleted == null)) {
                this.SelectDataXmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectDataXmlOperationCompleted);
            }
            this.InvokeAsync("SelectDataXml", new object[] {
                        Request}, this.SelectDataXmlOperationCompleted, userState);
        }
        
        private void OnSelectDataXmlOperationCompleted(object arg) {
            if ((this.SelectDataXmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectDataXmlCompleted(this, new SelectDataXmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://clients.mindbodyonline.com/api/0_5/SelectDataCSV", RequestNamespace="http://clients.mindbodyonline.com/api/0_5", ResponseNamespace="http://clients.mindbodyonline.com/api/0_5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SelectDataCSVResult SelectDataCSV(SelectDataCSVRequest Request) {
            object[] results = this.Invoke("SelectDataCSV", new object[] {
                        Request});
            return ((SelectDataCSVResult)(results[0]));
        }
        
        /// <remarks/>
        public void SelectDataCSVAsync(SelectDataCSVRequest Request) {
            this.SelectDataCSVAsync(Request, null);
        }
        
        /// <remarks/>
        public void SelectDataCSVAsync(SelectDataCSVRequest Request, object userState) {
            if ((this.SelectDataCSVOperationCompleted == null)) {
                this.SelectDataCSVOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectDataCSVOperationCompleted);
            }
            this.InvokeAsync("SelectDataCSV", new object[] {
                        Request}, this.SelectDataCSVOperationCompleted, userState);
        }
        
        private void OnSelectDataCSVOperationCompleted(object arg) {
            if ((this.SelectDataCSVCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectDataCSVCompleted(this, new SelectDataCSVCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://clients.mindbodyonline.com/api/0_5/SelectAggregateDataXml", RequestNamespace="http://clients.mindbodyonline.com/api/0_5", ResponseNamespace="http://clients.mindbodyonline.com/api/0_5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SelectAggregateDataXmlResult SelectAggregateDataXml(SelectAggregateDataXmlRequest Request) {
            object[] results = this.Invoke("SelectAggregateDataXml", new object[] {
                        Request});
            return ((SelectAggregateDataXmlResult)(results[0]));
        }
        
        /// <remarks/>
        public void SelectAggregateDataXmlAsync(SelectAggregateDataXmlRequest Request) {
            this.SelectAggregateDataXmlAsync(Request, null);
        }
        
        /// <remarks/>
        public void SelectAggregateDataXmlAsync(SelectAggregateDataXmlRequest Request, object userState) {
            if ((this.SelectAggregateDataXmlOperationCompleted == null)) {
                this.SelectAggregateDataXmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectAggregateDataXmlOperationCompleted);
            }
            this.InvokeAsync("SelectAggregateDataXml", new object[] {
                        Request}, this.SelectAggregateDataXmlOperationCompleted, userState);
        }
        
        private void OnSelectAggregateDataXmlOperationCompleted(object arg) {
            if ((this.SelectAggregateDataXmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectAggregateDataXmlCompleted(this, new SelectAggregateDataXmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://clients.mindbodyonline.com/api/0_5/SelectAggregateDataCSV", RequestNamespace="http://clients.mindbodyonline.com/api/0_5", ResponseNamespace="http://clients.mindbodyonline.com/api/0_5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SelectAggregateDataCSVResult SelectAggregateDataCSV(SelectAggregateDataCSVRequest Request) {
            object[] results = this.Invoke("SelectAggregateDataCSV", new object[] {
                        Request});
            return ((SelectAggregateDataCSVResult)(results[0]));
        }
        
        /// <remarks/>
        public void SelectAggregateDataCSVAsync(SelectAggregateDataCSVRequest Request) {
            this.SelectAggregateDataCSVAsync(Request, null);
        }
        
        /// <remarks/>
        public void SelectAggregateDataCSVAsync(SelectAggregateDataCSVRequest Request, object userState) {
            if ((this.SelectAggregateDataCSVOperationCompleted == null)) {
                this.SelectAggregateDataCSVOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectAggregateDataCSVOperationCompleted);
            }
            this.InvokeAsync("SelectAggregateDataCSV", new object[] {
                        Request}, this.SelectAggregateDataCSVOperationCompleted, userState);
        }
        
        private void OnSelectAggregateDataCSVOperationCompleted(object arg) {
            if ((this.SelectAggregateDataCSVCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectAggregateDataCSVCompleted(this, new SelectAggregateDataCSVCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class SelectDataXmlRequest : MBRequest {
        
        private string selectSqlField;
        
        /// <remarks/>
        public string SelectSql {
            get {
                return this.selectSqlField;
            }
            set {
                this.selectSqlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SelectAggregateDataCSVRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SelectAggregateDataXmlRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SelectDataCSVRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SelectDataXmlRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class MBRequest {
        
        private SourceCredentials sourceCredentialsField;
        
        private UserCredentials userCredentialsField;
        
        private System.Nullable<XMLDetailLevel> xMLDetailField;
        
        private System.Nullable<int> pageSizeField;
        
        private System.Nullable<int> currentPageIndexField;
        
        private string[] fieldsField;
        
        /// <remarks/>
        public SourceCredentials SourceCredentials {
            get {
                return this.sourceCredentialsField;
            }
            set {
                this.sourceCredentialsField = value;
            }
        }
        
        /// <remarks/>
        public UserCredentials UserCredentials {
            get {
                return this.userCredentialsField;
            }
            set {
                this.userCredentialsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<XMLDetailLevel> XMLDetail {
            get {
                return this.xMLDetailField;
            }
            set {
                this.xMLDetailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> PageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CurrentPageIndex {
            get {
                return this.currentPageIndexField;
            }
            set {
                this.currentPageIndexField = value;
            }
        }
        
        /// <remarks/>
        public string[] Fields {
            get {
                return this.fieldsField;
            }
            set {
                this.fieldsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class SourceCredentials {
        
        private string sourceNameField;
        
        private string passwordField;
        
        private int[] siteIDsField;
        
        /// <remarks/>
        public string SourceName {
            get {
                return this.sourceNameField;
            }
            set {
                this.sourceNameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public int[] SiteIDs {
            get {
                return this.siteIDsField;
            }
            set {
                this.siteIDsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/API/0_4")]
    public partial class Row {
        
        private object contentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SelectAggregateDataCSVResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SelectAggregateDataXmlResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SelectDataCSVResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SelectDataXmlResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class MBResult {
        
        private StatusCode statusField;
        
        private string messageField;
        
        private XMLDetailLevel xMLDetailField;
        
        private int resultCountField;
        
        private int currentPageIndexField;
        
        private int totalPageCountField;
        
        /// <remarks/>
        public StatusCode Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public XMLDetailLevel XMLDetail {
            get {
                return this.xMLDetailField;
            }
            set {
                this.xMLDetailField = value;
            }
        }
        
        /// <remarks/>
        public int ResultCount {
            get {
                return this.resultCountField;
            }
            set {
                this.resultCountField = value;
            }
        }
        
        /// <remarks/>
        public int CurrentPageIndex {
            get {
                return this.currentPageIndexField;
            }
            set {
                this.currentPageIndexField = value;
            }
        }
        
        /// <remarks/>
        public int TotalPageCount {
            get {
                return this.totalPageCountField;
            }
            set {
                this.totalPageCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public enum StatusCode {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        InvalidCredentials,
        
        /// <remarks/>
        InvalidParameters,
        
        /// <remarks/>
        InternalException,
        
        /// <remarks/>
        Unknown,
        
        /// <remarks/>
        FailedAction,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public enum XMLDetailLevel {
        
        /// <remarks/>
        Bare,
        
        /// <remarks/>
        Basic,
        
        /// <remarks/>
        Full,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class SelectAggregateDataCSVResult : MBResult {
        
        private string cSVField;
        
        /// <remarks/>
        public string CSV {
            get {
                return this.cSVField;
            }
            set {
                this.cSVField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class SelectAggregateDataXmlResult : MBResult {
        
        private Row[] resultsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Row[] Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class SelectDataCSVResult : MBResult {
        
        private string cSVField;
        
        /// <remarks/>
        public string CSV {
            get {
                return this.cSVField;
            }
            set {
                this.cSVField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class SelectDataXmlResult : MBResult {
        
        private Row[] resultsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Row[] Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class UserCredentials {
        
        private string usernameField;
        
        private string passwordField;
        
        private int[] siteIDsField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public int[] SiteIDs {
            get {
                return this.siteIDsField;
            }
            set {
                this.siteIDsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class SelectAggregateDataCSVRequest : MBRequest {
        
        private string selectSqlField;
        
        /// <remarks/>
        public string SelectSql {
            get {
                return this.selectSqlField;
            }
            set {
                this.selectSqlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class SelectAggregateDataXmlRequest : MBRequest {
        
        private string selectSqlField;
        
        /// <remarks/>
        public string SelectSql {
            get {
                return this.selectSqlField;
            }
            set {
                this.selectSqlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class SelectDataCSVRequest : MBRequest {
        
        private string selectSqlField;
        
        /// <remarks/>
        public string SelectSql {
            get {
                return this.selectSqlField;
            }
            set {
                this.selectSqlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SelectDataXmlCompletedEventHandler(object sender, SelectDataXmlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectDataXmlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectDataXmlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SelectDataXmlResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SelectDataXmlResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SelectDataCSVCompletedEventHandler(object sender, SelectDataCSVCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectDataCSVCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectDataCSVCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SelectDataCSVResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SelectDataCSVResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SelectAggregateDataXmlCompletedEventHandler(object sender, SelectAggregateDataXmlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectAggregateDataXmlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectAggregateDataXmlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SelectAggregateDataXmlResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SelectAggregateDataXmlResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SelectAggregateDataCSVCompletedEventHandler(object sender, SelectAggregateDataCSVCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectAggregateDataCSVCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectAggregateDataCSVCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SelectAggregateDataCSVResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SelectAggregateDataCSVResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591