//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.269.
// 
#pragma warning disable 1591

namespace API_Example.SiteService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Site ServiceSoap", Namespace="http://clients.mindbodyonline.com/api/0_5")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MBObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MBResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MBRequest))]
    public partial class SiteService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetSitesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLocationsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetActivationCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProgramsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSessionTypesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetResourcesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRelationshipsOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddSiteToCredentialsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SiteService() {
            this.Url = global::API_Example.Properties.Settings.Default.API_Example_mindbodyonline_api_siteservice_Site_x0020_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetSitesCompletedEventHandler GetSitesCompleted;
        
        /// <remarks/>
        public event GetLocationsCompletedEventHandler GetLocationsCompleted;
        
        /// <remarks/>
        public event GetActivationCodeCompletedEventHandler GetActivationCodeCompleted;
        
        /// <remarks/>
        public event GetProgramsCompletedEventHandler GetProgramsCompleted;
        
        /// <remarks/>
        public event GetSessionTypesCompletedEventHandler GetSessionTypesCompleted;
        
        /// <remarks/>
        public event GetResourcesCompletedEventHandler GetResourcesCompleted;
        
        /// <remarks/>
        public event GetRelationshipsCompletedEventHandler GetRelationshipsCompleted;
        
        /// <remarks/>
        public event AddSiteToCredentialsCompletedEventHandler AddSiteToCredentialsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://clients.mindbodyonline.com/api/0_5/GetSites", RequestNamespace="http://clients.mindbodyonline.com/api/0_5", ResponseNamespace="http://clients.mindbodyonline.com/api/0_5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetSitesResult GetSites(GetSitesRequest Request) {
            object[] results = this.Invoke("GetSites", new object[] {
                        Request});
            return ((GetSitesResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetSitesAsync(GetSitesRequest Request) {
            this.GetSitesAsync(Request, null);
        }
        
        /// <remarks/>
        public void GetSitesAsync(GetSitesRequest Request, object userState) {
            if ((this.GetSitesOperationCompleted == null)) {
                this.GetSitesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSitesOperationCompleted);
            }
            this.InvokeAsync("GetSites", new object[] {
                        Request}, this.GetSitesOperationCompleted, userState);
        }
        
        private void OnGetSitesOperationCompleted(object arg) {
            if ((this.GetSitesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSitesCompleted(this, new GetSitesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://clients.mindbodyonline.com/api/0_5/GetLocations", RequestNamespace="http://clients.mindbodyonline.com/api/0_5", ResponseNamespace="http://clients.mindbodyonline.com/api/0_5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetLocationsResult GetLocations(GetLocationsRequest Request) {
            object[] results = this.Invoke("GetLocations", new object[] {
                        Request});
            return ((GetLocationsResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetLocationsAsync(GetLocationsRequest Request) {
            this.GetLocationsAsync(Request, null);
        }
        
        /// <remarks/>
        public void GetLocationsAsync(GetLocationsRequest Request, object userState) {
            if ((this.GetLocationsOperationCompleted == null)) {
                this.GetLocationsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLocationsOperationCompleted);
            }
            this.InvokeAsync("GetLocations", new object[] {
                        Request}, this.GetLocationsOperationCompleted, userState);
        }
        
        private void OnGetLocationsOperationCompleted(object arg) {
            if ((this.GetLocationsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLocationsCompleted(this, new GetLocationsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://clients.mindbodyonline.com/api/0_5/GetActivationCode", RequestNamespace="http://clients.mindbodyonline.com/api/0_5", ResponseNamespace="http://clients.mindbodyonline.com/api/0_5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetActivationCodeResult GetActivationCode(GetActivationCodeRequest Request) {
            object[] results = this.Invoke("GetActivationCode", new object[] {
                        Request});
            return ((GetActivationCodeResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetActivationCodeAsync(GetActivationCodeRequest Request) {
            this.GetActivationCodeAsync(Request, null);
        }
        
        /// <remarks/>
        public void GetActivationCodeAsync(GetActivationCodeRequest Request, object userState) {
            if ((this.GetActivationCodeOperationCompleted == null)) {
                this.GetActivationCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetActivationCodeOperationCompleted);
            }
            this.InvokeAsync("GetActivationCode", new object[] {
                        Request}, this.GetActivationCodeOperationCompleted, userState);
        }
        
        private void OnGetActivationCodeOperationCompleted(object arg) {
            if ((this.GetActivationCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetActivationCodeCompleted(this, new GetActivationCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://clients.mindbodyonline.com/api/0_5/GetPrograms", RequestNamespace="http://clients.mindbodyonline.com/api/0_5", ResponseNamespace="http://clients.mindbodyonline.com/api/0_5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetProgramsResult GetPrograms(GetProgramsRequest Request) {
            object[] results = this.Invoke("GetPrograms", new object[] {
                        Request});
            return ((GetProgramsResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetProgramsAsync(GetProgramsRequest Request) {
            this.GetProgramsAsync(Request, null);
        }
        
        /// <remarks/>
        public void GetProgramsAsync(GetProgramsRequest Request, object userState) {
            if ((this.GetProgramsOperationCompleted == null)) {
                this.GetProgramsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProgramsOperationCompleted);
            }
            this.InvokeAsync("GetPrograms", new object[] {
                        Request}, this.GetProgramsOperationCompleted, userState);
        }
        
        private void OnGetProgramsOperationCompleted(object arg) {
            if ((this.GetProgramsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProgramsCompleted(this, new GetProgramsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://clients.mindbodyonline.com/api/0_5/GetSessionTypes", RequestNamespace="http://clients.mindbodyonline.com/api/0_5", ResponseNamespace="http://clients.mindbodyonline.com/api/0_5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetSessionTypesResult GetSessionTypes(GetSessionTypesRequest Request) {
            object[] results = this.Invoke("GetSessionTypes", new object[] {
                        Request});
            return ((GetSessionTypesResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetSessionTypesAsync(GetSessionTypesRequest Request) {
            this.GetSessionTypesAsync(Request, null);
        }
        
        /// <remarks/>
        public void GetSessionTypesAsync(GetSessionTypesRequest Request, object userState) {
            if ((this.GetSessionTypesOperationCompleted == null)) {
                this.GetSessionTypesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSessionTypesOperationCompleted);
            }
            this.InvokeAsync("GetSessionTypes", new object[] {
                        Request}, this.GetSessionTypesOperationCompleted, userState);
        }
        
        private void OnGetSessionTypesOperationCompleted(object arg) {
            if ((this.GetSessionTypesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSessionTypesCompleted(this, new GetSessionTypesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://clients.mindbodyonline.com/api/0_5/GetResources", RequestNamespace="http://clients.mindbodyonline.com/api/0_5", ResponseNamespace="http://clients.mindbodyonline.com/api/0_5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetResourcesResult GetResources(GetResourcesRequest Request) {
            object[] results = this.Invoke("GetResources", new object[] {
                        Request});
            return ((GetResourcesResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetResourcesAsync(GetResourcesRequest Request) {
            this.GetResourcesAsync(Request, null);
        }
        
        /// <remarks/>
        public void GetResourcesAsync(GetResourcesRequest Request, object userState) {
            if ((this.GetResourcesOperationCompleted == null)) {
                this.GetResourcesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetResourcesOperationCompleted);
            }
            this.InvokeAsync("GetResources", new object[] {
                        Request}, this.GetResourcesOperationCompleted, userState);
        }
        
        private void OnGetResourcesOperationCompleted(object arg) {
            if ((this.GetResourcesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetResourcesCompleted(this, new GetResourcesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://clients.mindbodyonline.com/api/0_5/GetRelationships", RequestNamespace="http://clients.mindbodyonline.com/api/0_5", ResponseNamespace="http://clients.mindbodyonline.com/api/0_5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetRelationshipsResult GetRelationships(GetRelationshipsRequest Request) {
            object[] results = this.Invoke("GetRelationships", new object[] {
                        Request});
            return ((GetRelationshipsResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetRelationshipsAsync(GetRelationshipsRequest Request) {
            this.GetRelationshipsAsync(Request, null);
        }
        
        /// <remarks/>
        public void GetRelationshipsAsync(GetRelationshipsRequest Request, object userState) {
            if ((this.GetRelationshipsOperationCompleted == null)) {
                this.GetRelationshipsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRelationshipsOperationCompleted);
            }
            this.InvokeAsync("GetRelationships", new object[] {
                        Request}, this.GetRelationshipsOperationCompleted, userState);
        }
        
        private void OnGetRelationshipsOperationCompleted(object arg) {
            if ((this.GetRelationshipsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRelationshipsCompleted(this, new GetRelationshipsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://clients.mindbodyonline.com/api/0_5/AddSiteToCredentials", RequestNamespace="http://clients.mindbodyonline.com/api/0_5", ResponseNamespace="http://clients.mindbodyonline.com/api/0_5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AddSiteToCredentialsResult AddSiteToCredentials(AddSiteToCredentialsRequest Request) {
            object[] results = this.Invoke("AddSiteToCredentials", new object[] {
                        Request});
            return ((AddSiteToCredentialsResult)(results[0]));
        }
        
        /// <remarks/>
        public void AddSiteToCredentialsAsync(AddSiteToCredentialsRequest Request) {
            this.AddSiteToCredentialsAsync(Request, null);
        }
        
        /// <remarks/>
        public void AddSiteToCredentialsAsync(AddSiteToCredentialsRequest Request, object userState) {
            if ((this.AddSiteToCredentialsOperationCompleted == null)) {
                this.AddSiteToCredentialsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddSiteToCredentialsOperationCompleted);
            }
            this.InvokeAsync("AddSiteToCredentials", new object[] {
                        Request}, this.AddSiteToCredentialsOperationCompleted, userState);
        }
        
        private void OnAddSiteToCredentialsOperationCompleted(object arg) {
            if ((this.AddSiteToCredentialsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddSiteToCredentialsCompleted(this, new AddSiteToCredentialsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class GetSitesRequest : MBRequest {
        
        private string searchTextField;
        
        private System.Nullable<int> relatedSiteIDField;
        
        /// <remarks/>
        public string SearchText {
            get {
                return this.searchTextField;
            }
            set {
                this.searchTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> RelatedSiteID {
            get {
                return this.relatedSiteIDField;
            }
            set {
                this.relatedSiteIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AddSiteToCredentialsRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetRelationshipsRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetResourcesRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetSessionTypesRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetProgramsRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetActivationCodeRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetLocationsRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetSitesRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class MBRequest {
        
        private SourceCredentials sourceCredentialsField;
        
        private UserCredentials userCredentialsField;
        
        private System.Nullable<XMLDetailLevel> xMLDetailField;
        
        private System.Nullable<int> pageSizeField;
        
        private System.Nullable<int> currentPageIndexField;
        
        private string[] fieldsField;
        
        /// <remarks/>
        public SourceCredentials SourceCredentials {
            get {
                return this.sourceCredentialsField;
            }
            set {
                this.sourceCredentialsField = value;
            }
        }
        
        /// <remarks/>
        public UserCredentials UserCredentials {
            get {
                return this.userCredentialsField;
            }
            set {
                this.userCredentialsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<XMLDetailLevel> XMLDetail {
            get {
                return this.xMLDetailField;
            }
            set {
                this.xMLDetailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> PageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CurrentPageIndex {
            get {
                return this.currentPageIndexField;
            }
            set {
                this.currentPageIndexField = value;
            }
        }
        
        /// <remarks/>
        public string[] Fields {
            get {
                return this.fieldsField;
            }
            set {
                this.fieldsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class SourceCredentials {
        
        private string sourceNameField;
        
        private string passwordField;
        
        private int[] siteIDsField;
        
        /// <remarks/>
        public string SourceName {
            get {
                return this.sourceNameField;
            }
            set {
                this.sourceNameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public int[] SiteIDs {
            get {
                return this.siteIDsField;
            }
            set {
                this.siteIDsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class Relationship {
        
        private int idField;
        
        private string relationshipName1Field;
        
        private string relationshipName2Field;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string RelationshipName1 {
            get {
                return this.relationshipName1Field;
            }
            set {
                this.relationshipName1Field = value;
            }
        }
        
        /// <remarks/>
        public string RelationshipName2 {
            get {
                return this.relationshipName2Field;
            }
            set {
                this.relationshipName2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Resource))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SessionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Program))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Location))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class MBObject {
        
        private Site siteField;
        
        private string[] messagesField;
        
        private string executeField;
        
        /// <remarks/>
        public Site Site {
            get {
                return this.siteField;
            }
            set {
                this.siteField = value;
            }
        }
        
        /// <remarks/>
        public string[] Messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
            }
        }
        
        /// <remarks/>
        public string Execute {
            get {
                return this.executeField;
            }
            set {
                this.executeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class Site {
        
        private int idField;
        
        private string nameField;
        
        private string descriptionField;
        
        private string logoURLField;
        
        private string pageColor1Field;
        
        private string pageColor2Field;
        
        private string pageColor3Field;
        
        private string pageColor4Field;
        
        private bool acceptsVisaField;
        
        private bool acceptsVisaFieldSpecified;
        
        private bool acceptsDiscoverField;
        
        private bool acceptsDiscoverFieldSpecified;
        
        private bool acceptsMasterCardField;
        
        private bool acceptsMasterCardFieldSpecified;
        
        private bool acceptsAmericanExpressField;
        
        private bool acceptsAmericanExpressFieldSpecified;
        
        private string contactEmailField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string LogoURL {
            get {
                return this.logoURLField;
            }
            set {
                this.logoURLField = value;
            }
        }
        
        /// <remarks/>
        public string PageColor1 {
            get {
                return this.pageColor1Field;
            }
            set {
                this.pageColor1Field = value;
            }
        }
        
        /// <remarks/>
        public string PageColor2 {
            get {
                return this.pageColor2Field;
            }
            set {
                this.pageColor2Field = value;
            }
        }
        
        /// <remarks/>
        public string PageColor3 {
            get {
                return this.pageColor3Field;
            }
            set {
                this.pageColor3Field = value;
            }
        }
        
        /// <remarks/>
        public string PageColor4 {
            get {
                return this.pageColor4Field;
            }
            set {
                this.pageColor4Field = value;
            }
        }
        
        /// <remarks/>
        public bool AcceptsVisa {
            get {
                return this.acceptsVisaField;
            }
            set {
                this.acceptsVisaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AcceptsVisaSpecified {
            get {
                return this.acceptsVisaFieldSpecified;
            }
            set {
                this.acceptsVisaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool AcceptsDiscover {
            get {
                return this.acceptsDiscoverField;
            }
            set {
                this.acceptsDiscoverField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AcceptsDiscoverSpecified {
            get {
                return this.acceptsDiscoverFieldSpecified;
            }
            set {
                this.acceptsDiscoverFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool AcceptsMasterCard {
            get {
                return this.acceptsMasterCardField;
            }
            set {
                this.acceptsMasterCardField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AcceptsMasterCardSpecified {
            get {
                return this.acceptsMasterCardFieldSpecified;
            }
            set {
                this.acceptsMasterCardFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool AcceptsAmericanExpress {
            get {
                return this.acceptsAmericanExpressField;
            }
            set {
                this.acceptsAmericanExpressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AcceptsAmericanExpressSpecified {
            get {
                return this.acceptsAmericanExpressFieldSpecified;
            }
            set {
                this.acceptsAmericanExpressFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string ContactEmail {
            get {
                return this.contactEmailField;
            }
            set {
                this.contactEmailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class Resource : MBObject {
        
        private ActionCode actionField;
        
        private bool actionFieldSpecified;
        
        private System.Nullable<int> idField;
        
        private bool idFieldSpecified;
        
        private string nameField;
        
        /// <remarks/>
        public ActionCode Action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActionSpecified {
            get {
                return this.actionFieldSpecified;
            }
            set {
                this.actionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IDSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public enum ActionCode {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Added,
        
        /// <remarks/>
        Updated,
        
        /// <remarks/>
        Failed,
        
        /// <remarks/>
        Removed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class SessionType : MBObject {
        
        private ActionCode actionField;
        
        private bool actionFieldSpecified;
        
        private System.Nullable<int> idField;
        
        private bool idFieldSpecified;
        
        private string nameField;
        
        /// <remarks/>
        public ActionCode Action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActionSpecified {
            get {
                return this.actionFieldSpecified;
            }
            set {
                this.actionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IDSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class Program : MBObject {
        
        private int idField;
        
        private string nameField;
        
        private System.Nullable<ScheduleType> scheduleTypeField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<ScheduleType> ScheduleType {
            get {
                return this.scheduleTypeField;
            }
            set {
                this.scheduleTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public enum ScheduleType {
        
        /// <remarks/>
        All,
        
        /// <remarks/>
        DropIn,
        
        /// <remarks/>
        Enrollment,
        
        /// <remarks/>
        Appointment,
        
        /// <remarks/>
        Resource,
        
        /// <remarks/>
        Media,
        
        /// <remarks/>
        Arrival,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class Location : MBObject {
        
        private System.Nullable<int> businessIDField;
        
        private bool businessIDFieldSpecified;
        
        private int siteIDField;
        
        private bool siteIDFieldSpecified;
        
        private string businessDescriptionField;
        
        private string[] additionalImageURLsField;
        
        private System.Nullable<int> facilitySquareFeetField;
        
        private bool facilitySquareFeetFieldSpecified;
        
        private System.Nullable<int> treatmentRoomsField;
        
        private bool treatmentRoomsFieldSpecified;
        
        private bool proSpaFinderSiteField;
        
        private bool proSpaFinderSiteFieldSpecified;
        
        private bool hasClassesField;
        
        private bool hasClassesFieldSpecified;
        
        private string phoneExtensionField;
        
        private ActionCode actionField;
        
        private bool actionFieldSpecified;
        
        private System.Nullable<int> idField;
        
        private bool idFieldSpecified;
        
        private string nameField;
        
        private string addressField;
        
        private string address2Field;
        
        private System.Nullable<float> tax1Field;
        
        private bool tax1FieldSpecified;
        
        private System.Nullable<float> tax2Field;
        
        private bool tax2FieldSpecified;
        
        private System.Nullable<float> tax3Field;
        
        private bool tax3FieldSpecified;
        
        private System.Nullable<float> tax4Field;
        
        private bool tax4FieldSpecified;
        
        private System.Nullable<float> tax5Field;
        
        private bool tax5FieldSpecified;
        
        private string phoneField;
        
        private string cityField;
        
        private string stateProvCodeField;
        
        private string postalCodeField;
        
        private System.Nullable<double> latitudeField;
        
        private bool latitudeFieldSpecified;
        
        private System.Nullable<double> longitudeField;
        
        private bool longitudeFieldSpecified;
        
        private System.Nullable<double> distanceInMilesField;
        
        private bool distanceInMilesFieldSpecified;
        
        private string imageURLField;
        
        private string descriptionField;
        
        private System.Nullable<bool> hasSiteField;
        
        private bool hasSiteFieldSpecified;
        
        private System.Nullable<bool> canBookField;
        
        private bool canBookFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> BusinessID {
            get {
                return this.businessIDField;
            }
            set {
                this.businessIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BusinessIDSpecified {
            get {
                return this.businessIDFieldSpecified;
            }
            set {
                this.businessIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int SiteID {
            get {
                return this.siteIDField;
            }
            set {
                this.siteIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SiteIDSpecified {
            get {
                return this.siteIDFieldSpecified;
            }
            set {
                this.siteIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string BusinessDescription {
            get {
                return this.businessDescriptionField;
            }
            set {
                this.businessDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string[] AdditionalImageURLs {
            get {
                return this.additionalImageURLsField;
            }
            set {
                this.additionalImageURLsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> FacilitySquareFeet {
            get {
                return this.facilitySquareFeetField;
            }
            set {
                this.facilitySquareFeetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FacilitySquareFeetSpecified {
            get {
                return this.facilitySquareFeetFieldSpecified;
            }
            set {
                this.facilitySquareFeetFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> TreatmentRooms {
            get {
                return this.treatmentRoomsField;
            }
            set {
                this.treatmentRoomsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TreatmentRoomsSpecified {
            get {
                return this.treatmentRoomsFieldSpecified;
            }
            set {
                this.treatmentRoomsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool ProSpaFinderSite {
            get {
                return this.proSpaFinderSiteField;
            }
            set {
                this.proSpaFinderSiteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProSpaFinderSiteSpecified {
            get {
                return this.proSpaFinderSiteFieldSpecified;
            }
            set {
                this.proSpaFinderSiteFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool HasClasses {
            get {
                return this.hasClassesField;
            }
            set {
                this.hasClassesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HasClassesSpecified {
            get {
                return this.hasClassesFieldSpecified;
            }
            set {
                this.hasClassesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string PhoneExtension {
            get {
                return this.phoneExtensionField;
            }
            set {
                this.phoneExtensionField = value;
            }
        }
        
        /// <remarks/>
        public ActionCode Action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActionSpecified {
            get {
                return this.actionFieldSpecified;
            }
            set {
                this.actionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IDSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string Address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<float> Tax1 {
            get {
                return this.tax1Field;
            }
            set {
                this.tax1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Tax1Specified {
            get {
                return this.tax1FieldSpecified;
            }
            set {
                this.tax1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<float> Tax2 {
            get {
                return this.tax2Field;
            }
            set {
                this.tax2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Tax2Specified {
            get {
                return this.tax2FieldSpecified;
            }
            set {
                this.tax2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<float> Tax3 {
            get {
                return this.tax3Field;
            }
            set {
                this.tax3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Tax3Specified {
            get {
                return this.tax3FieldSpecified;
            }
            set {
                this.tax3FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<float> Tax4 {
            get {
                return this.tax4Field;
            }
            set {
                this.tax4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Tax4Specified {
            get {
                return this.tax4FieldSpecified;
            }
            set {
                this.tax4FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<float> Tax5 {
            get {
                return this.tax5Field;
            }
            set {
                this.tax5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Tax5Specified {
            get {
                return this.tax5FieldSpecified;
            }
            set {
                this.tax5FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string StateProvCode {
            get {
                return this.stateProvCodeField;
            }
            set {
                this.stateProvCodeField = value;
            }
        }
        
        /// <remarks/>
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LatitudeSpecified {
            get {
                return this.latitudeFieldSpecified;
            }
            set {
                this.latitudeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LongitudeSpecified {
            get {
                return this.longitudeFieldSpecified;
            }
            set {
                this.longitudeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> DistanceInMiles {
            get {
                return this.distanceInMilesField;
            }
            set {
                this.distanceInMilesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DistanceInMilesSpecified {
            get {
                return this.distanceInMilesFieldSpecified;
            }
            set {
                this.distanceInMilesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string ImageURL {
            get {
                return this.imageURLField;
            }
            set {
                this.imageURLField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> HasSite {
            get {
                return this.hasSiteField;
            }
            set {
                this.hasSiteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HasSiteSpecified {
            get {
                return this.hasSiteFieldSpecified;
            }
            set {
                this.hasSiteFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> CanBook {
            get {
                return this.canBookField;
            }
            set {
                this.canBookField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CanBookSpecified {
            get {
                return this.canBookFieldSpecified;
            }
            set {
                this.canBookFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AddSiteToCredentialsResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetRelationshipsResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetResourcesResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetSessionTypesResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetProgramsResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetActivationCodeResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetLocationsResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetSitesResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class MBResult {
        
        private StatusCode statusField;
        
        private string messageField;
        
        private XMLDetailLevel xMLDetailField;
        
        private int resultCountField;
        
        private int currentPageIndexField;
        
        private int totalPageCountField;
        
        /// <remarks/>
        public StatusCode Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public XMLDetailLevel XMLDetail {
            get {
                return this.xMLDetailField;
            }
            set {
                this.xMLDetailField = value;
            }
        }
        
        /// <remarks/>
        public int ResultCount {
            get {
                return this.resultCountField;
            }
            set {
                this.resultCountField = value;
            }
        }
        
        /// <remarks/>
        public int CurrentPageIndex {
            get {
                return this.currentPageIndexField;
            }
            set {
                this.currentPageIndexField = value;
            }
        }
        
        /// <remarks/>
        public int TotalPageCount {
            get {
                return this.totalPageCountField;
            }
            set {
                this.totalPageCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public enum StatusCode {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        InvalidCredentials,
        
        /// <remarks/>
        InvalidParameters,
        
        /// <remarks/>
        InternalException,
        
        /// <remarks/>
        Unknown,
        
        /// <remarks/>
        FailedAction,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public enum XMLDetailLevel {
        
        /// <remarks/>
        Bare,
        
        /// <remarks/>
        Basic,
        
        /// <remarks/>
        Full,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class AddSiteToCredentialsResult : MBResult {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class GetRelationshipsResult : MBResult {
        
        private Relationship[] relationshipsField;
        
        /// <remarks/>
        public Relationship[] Relationships {
            get {
                return this.relationshipsField;
            }
            set {
                this.relationshipsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class GetResourcesResult : MBResult {
        
        private Resource[] resourcesField;
        
        /// <remarks/>
        public Resource[] Resources {
            get {
                return this.resourcesField;
            }
            set {
                this.resourcesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class GetSessionTypesResult : MBResult {
        
        private SessionType[] sessionTypesField;
        
        /// <remarks/>
        public SessionType[] SessionTypes {
            get {
                return this.sessionTypesField;
            }
            set {
                this.sessionTypesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class GetProgramsResult : MBResult {
        
        private Program[] programsField;
        
        /// <remarks/>
        public Program[] Programs {
            get {
                return this.programsField;
            }
            set {
                this.programsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class GetActivationCodeResult : MBResult {
        
        private string activationCodeField;
        
        private string activationLinkField;
        
        /// <remarks/>
        public string ActivationCode {
            get {
                return this.activationCodeField;
            }
            set {
                this.activationCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ActivationLink {
            get {
                return this.activationLinkField;
            }
            set {
                this.activationLinkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class GetLocationsResult : MBResult {
        
        private Location[] locationsField;
        
        /// <remarks/>
        public Location[] Locations {
            get {
                return this.locationsField;
            }
            set {
                this.locationsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class GetSitesResult : MBResult {
        
        private Site[] sitesField;
        
        /// <remarks/>
        public Site[] Sites {
            get {
                return this.sitesField;
            }
            set {
                this.sitesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class UserCredentials {
        
        private string usernameField;
        
        private string passwordField;
        
        private int[] siteIDsField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public int[] SiteIDs {
            get {
                return this.siteIDsField;
            }
            set {
                this.siteIDsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class AddSiteToCredentialsRequest : MBRequest {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class GetRelationshipsRequest : MBRequest {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class GetResourcesRequest : MBRequest {
        
        private int[] sessionTypeIDsField;
        
        private int locationIDField;
        
        private System.DateTime startDateTimeField;
        
        private System.DateTime endDateTimeField;
        
        /// <remarks/>
        public int[] SessionTypeIDs {
            get {
                return this.sessionTypeIDsField;
            }
            set {
                this.sessionTypeIDsField = value;
            }
        }
        
        /// <remarks/>
        public int LocationID {
            get {
                return this.locationIDField;
            }
            set {
                this.locationIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime StartDateTime {
            get {
                return this.startDateTimeField;
            }
            set {
                this.startDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EndDateTime {
            get {
                return this.endDateTimeField;
            }
            set {
                this.endDateTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class GetSessionTypesRequest : MBRequest {
        
        private int[] programIDsField;
        
        private bool onlineOnlyField;
        
        /// <remarks/>
        public int[] ProgramIDs {
            get {
                return this.programIDsField;
            }
            set {
                this.programIDsField = value;
            }
        }
        
        /// <remarks/>
        public bool OnlineOnly {
            get {
                return this.onlineOnlyField;
            }
            set {
                this.onlineOnlyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class GetProgramsRequest : MBRequest {
        
        private ScheduleType scheduleTypeField;
        
        private bool onlineOnlyField;
        
        /// <remarks/>
        public ScheduleType ScheduleType {
            get {
                return this.scheduleTypeField;
            }
            set {
                this.scheduleTypeField = value;
            }
        }
        
        /// <remarks/>
        public bool OnlineOnly {
            get {
                return this.onlineOnlyField;
            }
            set {
                this.onlineOnlyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class GetActivationCodeRequest : MBRequest {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class GetLocationsRequest : MBRequest {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetSitesCompletedEventHandler(object sender, GetSitesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSitesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSitesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetSitesResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetSitesResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetLocationsCompletedEventHandler(object sender, GetLocationsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLocationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLocationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetLocationsResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetLocationsResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetActivationCodeCompletedEventHandler(object sender, GetActivationCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetActivationCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetActivationCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetActivationCodeResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetActivationCodeResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetProgramsCompletedEventHandler(object sender, GetProgramsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProgramsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProgramsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetProgramsResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetProgramsResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetSessionTypesCompletedEventHandler(object sender, GetSessionTypesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSessionTypesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSessionTypesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetSessionTypesResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetSessionTypesResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetResourcesCompletedEventHandler(object sender, GetResourcesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetResourcesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetResourcesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetResourcesResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetResourcesResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetRelationshipsCompletedEventHandler(object sender, GetRelationshipsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRelationshipsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRelationshipsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetRelationshipsResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetRelationshipsResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AddSiteToCredentialsCompletedEventHandler(object sender, AddSiteToCredentialsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddSiteToCredentialsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddSiteToCredentialsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AddSiteToCredentialsResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AddSiteToCredentialsResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591