//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Example.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.mindbodyonline.com/0_5/ClassService.asmx")]
        public string API_Example_mindbodyonline_api_classservice_Class_x0020_Service {
            get {
                return ((string)(this["API_Example_mindbodyonline_api_classservice_Class_x0020_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.mindbodyonline.com/0_5/ClientService.asmx")]
        public string API_Example_mindbodyonline_api_clientservice_Client_x0020_Service {
            get {
                return ((string)(this["API_Example_mindbodyonline_api_clientservice_Client_x0020_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.mindbodyonline.com/0_5/AppointmentService.asmx")]
        public string API_Example_mindbodyonline_api_appointmentservice_Appointment_x0020_Service {
            get {
                return ((string)(this["API_Example_mindbodyonline_api_appointmentservice_Appointment_x0020_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.mindbodyonline.com/0_5/FinderService.asmx")]
        public string API_Example_mindbodyonline_api_finderservice_Finder_x0020_Service {
            get {
                return ((string)(this["API_Example_mindbodyonline_api_finderservice_Finder_x0020_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.mindbodyonline.com/0_5/DataService.asmx")]
        public string API_Example_mindbodyonline_api_dataservice_Data_x0020_Service {
            get {
                return ((string)(this["API_Example_mindbodyonline_api_dataservice_Data_x0020_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.mindbodyonline.com/0_5/SaleService.asmx")]
        public string API_Example_mindbodyonline_api_saleservice_Sale_x0020_Service {
            get {
                return ((string)(this["API_Example_mindbodyonline_api_saleservice_Sale_x0020_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.mindbodyonline.com/0_5/SiteService.asmx")]
        public string API_Example_mindbodyonline_api_siteservice_Site_x0020_Service {
            get {
                return ((string)(this["API_Example_mindbodyonline_api_siteservice_Site_x0020_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.mindbodyonline.com/0_5/StaffService.asmx")]
        public string API_Example_mindbodyonline_api_staffservice_Staff_x0020_Service {
            get {
                return ((string)(this["API_Example_mindbodyonline_api_staffservice_Staff_x0020_Service"]));
            }
        }
    }
}
